[colors.normal]
black = "0x1d2021"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[env]
WINIT_X11_SCALE_FACTOR = "1.1"

[font]
size = 15

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi"
mods = "Shift"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.92

[window.padding]
x = 10
y = 10
