#! /bin/sh

##########################################
# declaration of needed functions
##########################################

# handle setup of workspace (both in case of single and double monitor)
function setup_workspaces_monitor_polybar(){
	other_monitor=$(xrandr -q | awk '{if($2=="connected" && $1!="eDP1") {print $1}}')
	polybar example &

	if [[ -z ${other_monitor} ]] 
	then
		echo "Single monitor"
		bspc monitor -d I II III IV V VI VII VIII IX 
	else
		echo "Double monitor"

		xrandr --output eDP1 --primary --output "${other_monitor}" --right-of eDP1

		bspc monitor eDP1 -d I II III IV V
		bspc monitor "${other_monitor}" -d VI VII VIII IX
		
		# start polybar also on second monito
        polybar example_external &
	fi
}

##########################################

sxhkd &
picom &
wal -i /home/francesco/Pictures/ct0k3stx74541.jpg --backend wal --saturate 1.0 &
setxkbmap -layout it -variant us
dunst &
# source "/home/francesco/.cache/wal/colors.sh"

setup_workspaces_monitor_polybar


bspc config normal_border_color $color0
bspc config focused_border_color $color7
bspc config active_border_color $color1
bspc config urgent_border_color $color1
bspc config presel_feedback_color $color7

bspc config border_width             2
bspc config top_padding              22
bspc config bottom_padding           0
bspc config left_padding             0
bspc config right_padding            0
bspc config window_gap               9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config top_monocle_padding  -22

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc rule -a firefox desktop='^2' follow=on
